version: '2'
services:
    angularmongodb2018-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/AngularMongoDB2018/mongodb/:/data/db/
